name: Meson Build and Test
on:
  push:
    branches: [main]
    paths:
      - "**.cpp"
      - "**.h"
  pull_request:
    branches: [main]
    paths:
      - "**.cpp"
      - "**.h"

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        meson_version: ["1.4.1"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.16
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Fcitx5 dev packages
        run: sudo apt install -y fcitx5-modules-dev libfcitx5core-dev
      - name: Build and install Varnam
        run: |
          cd ../
          git clone https://github.com/varnamproject/govarnam.git govarnam
          cd govarnam
          make
          sudo make install
      - name: Install Meson
        run: python -m pip install meson==${{ matrix.meson_version }} ninja
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Project
        run: meson setup builddir/
        env:
          CC: g++
      - name: Run Build
        run: |
          cd builddir
          meson compile
      - name: Run Tests
        run: meson test -C builddir/ -v